
spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: hivelink_demo

  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.srmvxgtuytimdgksxnmn
    password: Manikeerthana
    driver-class-name: org.postgresql.Driver
    hikari:
      validation-timeout: 5000
      connection-timeout: 30000
      idle-timeout: 60000
      keepalive-time: 30000
      max-lifetime: 120000
      maximum-pool-size: 3
      minimum-idle: 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect